In [35]:
# Importer le librairies nécessaires 
import numpy as np #Pour tout ce qui est mathématiques 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression # Car on va utiliser une regression linéaire

In [36]:
#Emplacemnet du fichier courant
import os
os.getcwd()

'C:\\Users\\COMPTABILITE\\Desktop\\Mes formations\\Machine Learning avec Youtube\\Code Source et Data'

In [37]:
#Importer le dataset
Data = pd.read_excel('datas/VoitureOccasion.xlsx')

X = Data.iloc[:, :-1]
Y = Data.iloc[:, -1]

In [38]:
Data

    Année  Kilométrage  Nb chevaux    Marque    Prix
0    2005       250000           6      Audi   90000
1    2004       215000           7      Audi   85000
2    2010       145000           8       BMW  110000
3    2015        90000           6       BMW  130000
4    2017        65000           9  Mercedes  160000
5    2012       150000           7       BMW  120000
6    2010       160000           7      Audi   95000
7    2012       155000           7  Mercedes  120000
8    2015        85000           6       BMW  132000
9    2018        52000           6  Mercedes  175000
10   2014       130000           7      Audi  140000
11   2013       130000           7  Mercedes  140000
12   2013       170000           6       BMW  135000
13   2016       110000           6  Mercedes  155000
14   2019        55000           7      Audi  210000
15   2011       140000           7  Mercedes  111000
16   2009       185000           6       BMW   90000
17   2008       170000           6  Mercedes  105000
18   2016       105000           8      Audi  165000
19   2017        96000           8  Mercedes  190000
20   2010       210000           6  Mercedes  110000
21   2011       205000           7       BMW  100000
22   2011       215000           7  Mercedes  115000
23   2012       230000           6      Audi  115000
24   2012       235000           6  Mercedes  120000
25   2012       190000           8  Mercedes  110000
26   2017        76000           8       BMW  170000
27   2017        84000           6  Mercedes  195000
28   2017        84000           7      Audi  180000
29   2018        45000           7  Mercedes  220000
30   2014       180000           8      Audi  113500
31   2015       145000           6      Audi  145500
32   2013       130000           7       BMW  124500
33   2013       130000           7       BMW  125000
34   2014       174000           8  Mercedes  135000
35   2014       168000           6       BMW  135000
36   2015       136000           7      Audi  145000
37   2017        90000           7  Mercedes  190000
38   2017        85000           6       BMW  176000
39   2017        65000           6  Mercedes  205000
40   2012       230000           6      Audi  120000
41   2012       235000           6  Mercedes  117000
42   2013       190000           8  Mercedes  125000
43   2017        76000           8       BMW  168000
44   2017        84000           6  Mercedes  188000
45   2017        84000           7      Audi  180000
46   2018        45000           7  Mercedes  215000
47   2014       180000           8      Audi  113500
48   2015       145000           6      Audi  145500

In [39]:
X

    Année  Kilométrage  Nb chevaux    Marque
0    2005       250000           6      Audi
1    2004       215000           7      Audi
2    2010       145000           8       BMW
3    2015        90000           6       BMW
4    2017        65000           9  Mercedes
5    2012       150000           7       BMW
6    2010       160000           7      Audi
7    2012       155000           7  Mercedes
8    2015        85000           6       BMW
9    2018        52000           6  Mercedes
10   2014       130000           7      Audi
11   2013       130000           7  Mercedes
12   2013       170000           6       BMW
13   2016       110000           6  Mercedes
14   2019        55000           7      Audi
15   2011       140000           7  Mercedes
16   2009       185000           6       BMW
17   2008       170000           6  Mercedes
18   2016       105000           8      Audi
19   2017        96000           8  Mercedes
20   2010       210000           6  Mercedes
21   2011       205000           7       BMW
22   2011       215000           7  Mercedes
23   2012       230000           6      Audi
24   2012       235000           6  Mercedes
25   2012       190000           8  Mercedes
26   2017        76000           8       BMW
27   2017        84000           6  Mercedes
28   2017        84000           7      Audi
29   2018        45000           7  Mercedes
30   2014       180000           8      Audi
31   2015       145000           6      Audi
32   2013       130000           7       BMW
33   2013       130000           7       BMW
34   2014       174000           8  Mercedes
35   2014       168000           6       BMW
36   2015       136000           7      Audi
37   2017        90000           7  Mercedes
38   2017        85000           6       BMW
39   2017        65000           6  Mercedes
40   2012       230000           6      Audi
41   2012       235000           6  Mercedes
42   2013       190000           8  Mercedes
43   2017        76000           8       BMW
44   2017        84000           6  Mercedes
45   2017        84000           7      Audi
46   2018        45000           7  Mercedes
47   2014       180000           8      Audi
48   2015       145000           6      Audi

In [40]:
Y

0      90000
1      85000
2     110000
3     130000
4     160000
5     120000
6      95000
7     120000
8     132000
9     175000
10    140000
11    140000
12    135000
13    155000
14    210000
15    111000
16     90000
17    105000
18    165000
19    190000
20    110000
21    100000
22    115000
23    115000
24    120000
25    110000
26    170000
27    195000
28    180000
29    220000
30    113500
31    145500
32    124500
33    125000
34    135000
35    135000
36    145000
37    190000
38    176000
39    205000
40    120000
41    117000
42    125000
43    168000
44    188000
45    180000
46    215000
47    113500
48    145500
Name: Prix, dtype: int64

In [41]:
#Gérer les variables catégoriques
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer # Permet d'appliquer des transformations sur certaines colonnes spécifiques

# 3 c'est l'indice de la colone Marque sachant que la première colonne a poiyr indice 0
# remainder='passthrough' # Garde les autres colonnes sans modification
ct = ColumnTransformer([("Marque", OneHotEncoder(), [3])], remainder='passthrough' )
X = ct.fit_transform(X)

In [42]:
X

array([[1.000e+00, 0.000e+00, 0.000e+00, 2.005e+03, 2.500e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.004e+03, 2.150e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.010e+03, 1.450e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 9.000e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 9.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.012e+03, 1.500e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.010e+03, 1.600e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.550e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 8.500e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 5.200e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.700e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.016e+03, 1.100e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.019e+03, 5.500e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.011e+03, 1.400e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.009e+03, 1.850e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.008e+03, 1.700e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.016e+03, 1.050e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 9.600e+04, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.010e+03, 2.100e+05, 6.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.011e+03, 2.050e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.011e+03, 2.150e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.012e+03, 2.300e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 2.350e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.900e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.017e+03, 7.600e+04, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 8.400e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.017e+03, 8.400e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 4.500e+04, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.800e+05, 8.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.015e+03, 1.450e+05, 6.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.014e+03, 1.740e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.014e+03, 1.680e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.015e+03, 1.360e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 9.000e+04, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.017e+03, 8.500e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.012e+03, 2.300e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 2.350e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.013e+03, 1.900e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.017e+03, 7.600e+04, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 8.400e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.017e+03, 8.400e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 4.500e+04, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.800e+05, 8.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.015e+03, 1.450e+05, 6.000e+00]])

In [43]:
#Diviser le dataset
X_train, X_test, Y_train, Y_test =  train_test_split(X, Y, test_size=0.2)

In [44]:
X_train

array([[0.000e+00, 0.000e+00, 1.000e+00, 2.014e+03, 1.740e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.011e+03, 1.400e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.011e+03, 2.050e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 4.500e+04, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.019e+03, 5.500e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 8.400e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.010e+03, 2.100e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.900e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 4.500e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 9.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.014e+03, 1.680e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 8.400e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.800e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.013e+03, 1.900e+05, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 2.350e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.010e+03, 1.600e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 2.350e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.012e+03, 2.300e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.004e+03, 2.150e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.017e+03, 7.600e+04, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.700e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.015e+03, 1.450e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 9.000e+04, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.015e+03, 1.450e+05, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 9.600e+04, 8.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.550e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.017e+03, 8.500e+04, 6.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 8.500e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.016e+03, 1.050e+05, 8.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.015e+03, 1.360e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.300e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.017e+03, 8.400e+04, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.011e+03, 2.150e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.800e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.012e+03, 1.500e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 9.000e+04, 6.000e+00]])

In [45]:
#Construire le modèle
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [46]:
#Faire des prédictions
Y_pred = regressor.predict(X_test)

In [47]:
Y_pred

array([111202.16254782,  59043.29839932, 176658.61310129, 125071.9546971 ,
       109005.53722429,  94261.72684344,  90455.69504848, 159422.86187863,
       207248.29234918, 178471.61645681])

In [48]:
Y_test

23    115000
0      90000
45    180000
33    125000
17    105000
2     110000
16     90000
43    168000
9     175000
13    155000
Name: Prix, dtype: int64

In [49]:
#Prédire une voiture qui n'existe pas dans noter dtatset
                #    Marque(Mercedes)	   Année  Kilométrage Nb chevaux
regressor.predict([ [0, 0, 1,               2021,     9000,       6 ] ])

array([238737.79763642])

In [50]:
#Prédire une  seconde voiture qui n'existe pas dans noter dtatset
                #    Marque(Mercedes)	   Année  Kilométrage Nb chevaux
regressor.predict([ [0, 1, 0,               2012,     98000,       3 ] ])

array([153872.48382064])